# Generated by Django 4.1 on 2022-11-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="content", new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment", old_name="data_added", new_name="created_on",
        ),
    ]
