# Generated by Django 4.1 on 2022-11-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_content_comment_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="comment", new_name="content",
        ),
        migrations.RenameField(
            model_name="comment", old_name="created_on", new_name="data_added",
        ),
    ]
