# Generated by Django 4.1 on 2022-11-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_comment_comment_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user", new_name="author",
        ),
    ]
