# Generated by Django 4.1 on 2022-11-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gujarat_ngo",
            name="address",
            field=models.CharField(default="India", max_length=100),
        ),
        migrations.AlterField(
            model_name="gujarat_ngo",
            name="content",
            field=models.TextField(default="Ngo"),
        ),
        migrations.AlterField(
            model_name="gujarat_ngo",
            name="phone_number",
            field=models.CharField(default="123", max_length=20),
        ),
        migrations.AlterField(
            model_name="gujarat_ngo",
            name="title",
            field=models.CharField(default="Ngo", max_length=100),
        ),
    ]
